### ISSUE TITLE
Reinstate tracing parallel preloads

### ISSUE THREAD

**Issue by garthk** [spandex-project/spandex_ecto#12]
From the README:

> Due to some recent changes in Ecto, we can no longer effectively trace the execution of parallel preloads. All other queries work fine, but until we figure something out that leverages either telemetry or until the task feature listed [here](https://github.com/elixir-ecto/ecto/issues/2843) is added to the language, we won't be able to support tracing parallel preloads

@zachdaniel, in elixir-ecto/ecto#2843 you said `$callers` i.e. elixir-lang/elixir#7995 would be useful. They released that in Elixir 1.8. Was that the only blocker for preloads, or is more work required in Ecto?

You'd need to bump `version` for a breaking change due to `elixir: "~> 1.8"` in `def project`; would it also be time for 1.0.0?

**Comment by zachdaniel** [comment]
I don't know if it necessarily warrants a 1.0, but I definitely think that a new version could be released that looks for `$callers`. We don't even necessarily need to require elixir 1.8, because it is harmless to just check the process dictionary for callers. Would you be interested in working on that? Should be relatively easy to add.

**Comment by garthk** [comment]
If it turns out we’re using parallel preloads, sure. Would I need any more pointers than the diff in which you removed the old way of doing it?

**Comment by garthk** [comment]
Could you take as config a function returning the detail you need, leaving it up to the caller to register processes involved in a trace if they want this to work? Sorry if that’s poorly expressed, but I poorly understand the problem. :)

**Comment by zachdaniel** [comment]
We could leave it up the consumer of our library to implement a process registry of all traces, but at that point they're going to be writing about as much code as they are even getting from spandex at all anyway. Writing a trace/pid registration process and making it such that all traces/pids are registered is a hard-ish problem. Hard enough that it would be pretty strange to require it for this to work.

**Comment by garthk** [comment]
Closing while I concentrate on the Absinthe boundary.

**Comment by suppayami** [comment]
Regarding this issue, I think one solution is putting current trace/span to calling process and on parallel preload processes, we get dictionary info from caller process

`pid = List.last(Process.get(:"$callers"))`

**Comment by bjyoungblood** [comment]
I was able to get this working with a small wrapper around `SpandexEcto.TelemetryAdapter.handle_event/4` using [`:seq_trace`](https://erlang.org/doc/man/seq_trace.html). This could certainly use some cleanup, but it'd be a good starting point if anyone else is still looking for a solution in 2021. 😅 

This will only work on OTP >= 21. See the warning about label restrictions on [`:seq_trace.set_token/2`](https://erlang.org/doc/man/seq_trace.html#set_token-2).

Just use this when registering your telemetry events instead of `SpandexEcto.TelemetryAdapter`:

```elixir
defmodule MyApp.Tracer do
  use Spandex.Tracer, otp_app: :my_app

  def handle_event(event, measurements, metadata, config) do
    now = :os.system_time(:nano_seconds)

    started_trace? =
      case current_context() do
        {:ok, ctx} ->
          # any time we have an Ecto event with a trace context, save it in case
          # we need to continue later
          :seq_trace.set_token(:label, ctx)
          false

        {:error, :disabled} ->
          false

        {:error, reason} when reason in [:no_trace_context, :no_span_context] ->
          case :seq_trace.get_token(:label) do
            {:label, ctx} ->
              # TODO: handle options config like service. Maybe pull them from SpandexEcto.EctoLogger config
              continue_trace("async_query", ctx)

              true

            # no trace context was available
            _ ->
              false
          end
      end

    entry = SpandexEcto.TelemetryAdapter.handle_event(event, measurements, metadata, config)

    if started_trace? do
      queue_time = SpandexEcto.EctoLogger.get_time(entry, :queue_time)
      query_time = SpandexEcto.EctoLogger.get_time(entry, :query_time)
      decoding_time = SpandexEcto.EctoLogger.get_time(entry, :decode_time)
      update_span(completion_time: now, start: now - (queue_time + query_time + decoding_time))
      finish_trace()
    end
  end
end
```
